name: pub_patch

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org
      - name: install deps
        run: npm install
      - name: prepublish
        run: npm run prepublish
      - name: publish patch
        run: |
          git config --global user.name 'shenshuai89'
          git config --global user.email 'shenshuai89@qq.com'
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm run pub:patch
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
